#!/usr/local/bin/python3
import requests
import sys
from bs4 import BeautifulSoup
import json

def main():
    guild_ID=sys.argv[1]
    url_combined = str("https://web.rythmbot.co/ajax/shard/" + guild_ID)
    page = requests.get(url_combined)
    python_obj = json.loads(page.text)
    shard_ID=int(python_obj["shard"])
    cluster_ID=int(python_obj["cluster"])
    print(f"\nShard Number: {shard_ID}\nCluster Number: {cluster_ID}\n")
    rawstat = requests.get("https://status.rythmbot.co/raw")
    print(f"{shard_ID}:", json.loads(rawstat.text)[str(shard_ID)])
main()
