#!/usr/local/bin/python3
import requests
import sys
from bs4 import BeautifulSoup
import json

def main():
    guild_ID=sys.argv[1]
    url_combined = str("https://web.rythmbot.co/ajax/shard/" + guild_ID)
    page = requests.get(url_combined)
    python_obj = json.loads(page.text)
    guild_ID=int(python_obj["id"])
    shard_ID=int(python_obj["shard"])
    cluster_ID=int(python_obj["cluster"])
    print("\nShard Number: ", shard_ID, "\nCluster Number: ", cluster_ID, "\n")
    status = requests.get("https://status.rythmbot.co")
    soup = BeautifulSoup(status.text, 'html.parser')
    shard_s = soup.find(class_='container')
    shard_str=str(shard_s)
    shard_list = shard_str.split("</span><br/>\n<span class=\"bold\">")
    chosen_shard=str(shard_list[shard_ID])
    print(((chosen_shard.split("<"))[1].split(">"))[1]+((chosen_shard.split("<"))[3].split(">"))[1])

main()
